[package]
name = "classmesh-win32"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Environment",
    "Win32_System_IO",
    "Win32_System_Pipes",
    "Win32_System_RemoteDesktop",
    "Win32_System_Threading",
] }

[lints]
workspace = true
