[package]
name = "classmesh-windows-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
classmesh-core = { path = "../classmesh-core" }
classmesh-protocol = { path = "../classmesh-protocol" }
prost = "0.14.4"

[lints]
workspace = true
