[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("Help", "TransportServer", "TransportClient", "MediaReceiver", "MediaProxy", "MediaSender")]
    [string]$Mode,

    [ValidateSet("udp", "quic")]
    [string]$Transport = "udp",

    [string]$BinDir = ".",
    [string]$Listen = "",
    [string]$Peer = "",
    [int]$Seconds = 60,
    [int]$Pps = 500,
    [int]$PayloadBytes = 1000,
    [string]$CertPath = "classmesh-quic-cert.der",
    [int]$LossBp = 0,
    [int]$ReorderBp = 0,
    [int]$JitterMs = 0,
    [int]$ReorderDelayMs = 0,
    [UInt64]$Seed = 1,
    [string]$ResultsDir = "phase4-results"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Require-Value {
    param(
        [string]$Name,
        [string]$Value
    )

    if ([string]::IsNullOrWhiteSpace($Value)) {
        throw "$Name is required for mode $Mode"
    }
}

function Invoke-ClassMeshTool {
    param(
        [string]$Executable,
        [string[]]$Arguments,
        [string]$LogPrefix
    )

    $exePath = Join-Path $BinDir $Executable
    if (-not (Test-Path -LiteralPath $exePath -PathType Leaf)) {
        throw "Executable not found: $exePath"
    }

    New-Item -ItemType Directory -Path $ResultsDir -Force | Out-Null
    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $logPath = Join-Path $ResultsDir "$LogPrefix-$stamp.log"

    Write-Host "Running: $exePath $($Arguments -join ' ')"
    Write-Host "Log: $logPath"

    & $exePath @Arguments 2>&1 | Tee-Object -FilePath $logPath
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0) {
        throw "$Executable exited with code $exitCode. See $logPath"
    }

    Write-Host "Completed successfully. Log saved to $logPath"
}

function Show-Help {
    @"
ClassMesh Phase 4 two-PC qualification runner

Examples:
  # Student: healthy UDP synthetic benchmark server
  .\scripts\phase4-two-pc.ps1 -Mode TransportServer -Transport udp -BinDir .\artifacts

  # Teacher: healthy UDP synthetic benchmark client
  .\scripts\phase4-two-pc.ps1 -Mode TransportClient -Transport udp -Peer 192.168.1.20:57100 -BinDir .\artifacts

  # Student: QUIC server; writes the certificate that must be copied to Teacher
  .\scripts\phase4-two-pc.ps1 -Mode TransportServer -Transport quic -BinDir .\artifacts -CertPath .\classmesh-quic-cert.der

  # Teacher: QUIC client using copied DER certificate
  .\scripts\phase4-two-pc.ps1 -Mode TransportClient -Transport quic -Peer 192.168.1.20:57100 -BinDir .\artifacts -CertPath .\classmesh-quic-cert.der

  # Student: live H.264 hardware decode + D3D11 render + feedback to Teacher
  .\scripts\phase4-two-pc.ps1 -Mode MediaReceiver -Peer 192.168.1.10:57001 -BinDir .\artifacts -Seconds 120

  # Teacher: deterministic impairment proxy to Student (3% loss example)
  .\scripts\phase4-two-pc.ps1 -Mode MediaProxy -Peer 192.168.1.20:57000 -BinDir .\artifacts -LossBp 300 -JitterMs 20 -ReorderBp 300 -ReorderDelayMs 20 -Seconds 120

  # Teacher: capture/encode sender through local impairment proxy
  .\scripts\phase4-two-pc.ps1 -Mode MediaSender -BinDir .\artifacts -Seconds 120

Logs are written under -ResultsDir (default: .\phase4-results).
"@ | Write-Host
}

switch ($Mode) {
    "Help" {
        Show-Help
    }

    "TransportServer" {
        $effectiveListen = if ($Listen) { $Listen } else { "0.0.0.0:57100" }
        $arguments = @(
            "server",
            "--transport", $Transport,
            "--listen", $effectiveListen,
            "--seconds", "$Seconds"
        )
        if ($Transport -eq "quic") {
            $arguments += @("--cert-out", $CertPath)
        }
        Invoke-ClassMeshTool \
            -Executable "classmesh-transport-benchmark.exe" \
            -Arguments $arguments \
            -LogPrefix "transport-$Transport-server"
    }

    "TransportClient" {
        Require-Value -Name "-Peer <student-ip:57100>" -Value $Peer
        $arguments = @(
            "client",
            "--transport", $Transport,
            "--connect", $Peer,
            "--seconds", "$Seconds",
            "--pps", "$Pps",
            "--payload-bytes", "$PayloadBytes"
        )
        if ($Transport -eq "quic") {
            if (-not (Test-Path -LiteralPath $CertPath -PathType Leaf)) {
                throw "QUIC certificate not found: $CertPath. Copy the DER certificate generated by the Student server first."
            }
            $arguments += @("--cert", $CertPath)
        }
        Invoke-ClassMeshTool \
            -Executable "classmesh-transport-benchmark.exe" \
            -Arguments $arguments \
            -LogPrefix "transport-$Transport-client"
    }

    "MediaReceiver" {
        Require-Value -Name "-Peer <teacher-ip:57001>" -Value $Peer
        $effectiveListen = if ($Listen) { $Listen } else { "0.0.0.0:57000" }
        $arguments = @(
            "--listen", $effectiveListen,
            "--seconds", "$Seconds",
            "--render",
            "--feedback-to", $Peer
        )
        Invoke-ClassMeshTool \
            -Executable "classmesh-media-receiver.exe" \
            -Arguments $arguments \
            -LogPrefix "media-receiver"
    }

    "MediaProxy" {
        Require-Value -Name "-Peer <student-ip:57000>" -Value $Peer
        $effectiveListen = if ($Listen) { $Listen } else { "0.0.0.0:57010" }
        $arguments = @(
            "--listen", $effectiveListen,
            "--to", $Peer,
            "--seconds", "$Seconds",
            "--loss-bp", "$LossBp",
            "--reorder-bp", "$ReorderBp",
            "--jitter-ms", "$JitterMs",
            "--reorder-delay-ms", "$ReorderDelayMs",
            "--seed", "$Seed"
        )
        Invoke-ClassMeshTool \
            -Executable "classmesh-network-impairment-proxy.exe" \
            -Arguments $arguments \
            -LogPrefix "media-proxy-loss-$LossBp"
    }

    "MediaSender" {
        $effectivePeer = if ($Peer) { $Peer } else { "127.0.0.1:57010" }
        $effectiveListen = if ($Listen) { $Listen } else { "0.0.0.0:57001" }
        $arguments = @(
            "--seconds", "$Seconds",
            "--udp-to", $effectivePeer,
            "--feedback-listen", $effectiveListen
        )
        Invoke-ClassMeshTool \
            -Executable "classmesh-media-probe.exe" \
            -Arguments $arguments \
            -LogPrefix "media-sender"
    }
}