[package]
name = "classmesh-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
classmesh-windows-runtime = { path = "../../crates/classmesh-windows-runtime" }

[target.'cfg(windows)'.dependencies]
classmesh-win32 = { path = "../../crates/classmesh-win32" }
windows-service = "0.8.1"

[lints]
workspace = true
